/**
 * 数据库特定系统函数定义
 * 包含各主流数据库（MySQL、PostgreSQL、Oracle、SQL Server、达梦）的常用函数
 */

export const DatabaseFunctions = {
  mysql: [
    {
      name: 'CURRENT_DATE',
      description: '当前日期',
      syntax: 'CURRENT_DATE()',
      category: '日期时间',
    },
    {
      name: 'CURRENT_TIME',
      description: '当前时间',
      syntax: 'CURRENT_TIME()',
      category: '日期时间',
    },
    {
      name: 'CURRENT_TIMESTAMP',
      description: '当前时间戳',
      syntax: 'CURRENT_TIMESTAMP()',
      category: '日期时间',
    },
    { name: 'NOW', description: '当前日期时间', syntax: 'NOW()', category: '日期时间' },
    { name: 'SYSDATE', description: '系统日期时间', syntax: 'SYSDATE()', category: '日期时间' },
    { name: 'UUID', description: '生成唯一标识符', syntax: 'UUID()', category: '字符串' },
    { name: 'RAND', description: '生成随机数', syntax: 'RAND()', category: '数值' },
    {
      name: 'RAND',
      description: '生成指定范围的随机整数',
      syntax: 'RAND() * (max - min) + min',
      category: '数值',
      params: 'min, max',
    },
    {
      name: 'DATE_FORMAT',
      description: '格式化日期',
      syntax: "DATE_FORMAT(date, '%Y-%m-%d')",
      category: '日期时间',
      params: 'date, format',
    },
    {
      name: 'DATE_ADD',
      description: '日期加法',
      syntax: 'DATE_ADD(date, INTERVAL 1 DAY)',
      category: '日期时间',
      params: 'date, interval',
    },
    {
      name: 'DATEDIFF',
      description: '日期差值',
      syntax: 'DATEDIFF(date1, date2)',
      category: '日期时间',
      params: 'date1, date2',
    },
    {
      name: 'YEAR',
      description: '获取年份',
      syntax: 'YEAR(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'MONTH',
      description: '获取月份',
      syntax: 'MONTH(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'DAY',
      description: '获取日',
      syntax: 'DAY(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'HOUR',
      description: '获取小时',
      syntax: 'HOUR(time)',
      category: '日期时间',
      params: 'time',
    },
    {
      name: 'MINUTE',
      description: '获取分钟',
      syntax: 'MINUTE(time)',
      category: '日期时间',
      params: 'time',
    },
    {
      name: 'SECOND',
      description: '获取秒',
      syntax: 'SECOND(time)',
      category: '日期时间',
      params: 'time',
    },
    {
      name: 'UPPER',
      description: '转换为大写',
      syntax: 'UPPER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LOWER',
      description: '转换为小写',
      syntax: 'LOWER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'TRIM',
      description: '去除首尾空格',
      syntax: 'TRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LENGTH',
      description: '获取字符串长度',
      syntax: 'LENGTH(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'SUBSTRING',
      description: '截取字符串',
      syntax: 'SUBSTRING(str, start, length)',
      category: '字符串',
      params: 'str, start, length',
    },
    {
      name: 'CONCAT',
      description: '连接字符串',
      syntax: 'CONCAT(str1, str2, ...)',
      category: '字符串',
      params: 'str1, str2, ...',
    },
    {
      name: 'IFNULL',
      description: '如果为空则返回默认值',
      syntax: 'IFNULL(expr, default_value)',
      category: '条件',
      params: 'expr, default_value',
    },
    {
      name: 'NULLIF',
      description: '如果相等则返回NULL',
      syntax: 'NULLIF(expr1, expr2)',
      category: '条件',
      params: 'expr1, expr2',
    },
    {
      name: 'ROUND',
      description: '四舍五入',
      syntax: 'ROUND(number, decimals)',
      category: '数值',
      params: 'number, decimals',
    },
    {
      name: 'FLOOR',
      description: '向下取整',
      syntax: 'FLOOR(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'CEIL',
      description: '向上取整',
      syntax: 'CEIL(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'ABS',
      description: '绝对值',
      syntax: 'ABS(number)',
      category: '数值',
      params: 'number',
    },
    { name: 'MOD', description: '取模', syntax: 'MOD(a, b)', category: '数值', params: 'a, b' },
    { name: 'SUM', description: '求和', syntax: 'SUM(expr)', category: '聚合', params: 'expr' },
    { name: 'COUNT', description: '计数', syntax: 'COUNT(expr)', category: '聚合', params: 'expr' },
    { name: 'AVG', description: '平均值', syntax: 'AVG(expr)', category: '聚合', params: 'expr' },
    { name: 'MAX', description: '最大值', syntax: 'MAX(expr)', category: '聚合', params: 'expr' },
    { name: 'MIN', description: '最小值', syntax: 'MIN(expr)', category: '聚合', params: 'expr' },
    {
      name: 'LAST_INSERT_ID',
      description: '最后插入的ID',
      syntax: 'LAST_INSERT_ID()',
      category: '其他',
    },
    { name: 'DEFAULT', description: '使用列默认值', syntax: 'DEFAULT', category: '其他' },
  ],
  postgresql: [
    { name: 'CURRENT_DATE', description: '当前日期', syntax: 'CURRENT_DATE', category: '日期时间' },
    { name: 'CURRENT_TIME', description: '当前时间', syntax: 'CURRENT_TIME', category: '日期时间' },
    {
      name: 'CURRENT_TIMESTAMP',
      description: '当前时间戳',
      syntax: 'CURRENT_TIMESTAMP',
      category: '日期时间',
    },
    { name: 'NOW', description: '当前日期时间', syntax: 'NOW()', category: '日期时间' },
    {
      name: 'LOCALTIMESTAMP',
      description: '本地时间戳',
      syntax: 'LOCALTIMESTAMP',
      category: '日期时间',
    },
    {
      name: 'GEN_RANDOM_UUID',
      description: '生成UUID',
      syntax: 'GEN_RANDOM_UUID()',
      category: '字符串',
    },
    { name: 'RANDOM', description: '生成0-1随机数', syntax: 'RANDOM()', category: '数值' },
    {
      name: 'RANDOM',
      description: '生成指定范围随机整数',
      syntax: 'FLOOR(RANDOM() * (max - min + 1)) + min',
      category: '数值',
      params: 'min, max',
    },
    {
      name: 'TO_CHAR',
      description: '格式化日期',
      syntax: "TO_CHAR(date, 'YYYY-MM-DD')",
      category: '日期时间',
      params: 'date, format',
    },
    {
      name: 'TO_DATE',
      description: '字符串转日期',
      syntax: "TO_DATE('2024-01-01', 'YYYY-MM-DD')",
      category: '日期时间',
      params: 'str, format',
    },
    {
      name: 'DATE_TRUNC',
      description: '日期截断',
      syntax: "DATE_TRUNC('day', timestamp)",
      category: '日期时间',
      params: 'field, timestamp',
    },
    {
      name: 'EXTRACT',
      description: '提取日期部分',
      syntax: 'EXTRACT(YEAR FROM date)',
      category: '日期时间',
      params: 'field FROM date',
    },
    {
      name: 'AGE',
      description: '计算年龄',
      syntax: 'AGE(timestamp)',
      category: '日期时间',
      params: 'timestamp',
    },
    { name: 'INTERVAL', description: '时间间隔', syntax: "INTERVAL '1 day'", category: '日期时间' },
    {
      name: 'UPPER',
      description: '转换为大写',
      syntax: 'UPPER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LOWER',
      description: '转换为小写',
      syntax: 'LOWER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'TRIM',
      description: '去除首尾空格',
      syntax: 'TRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'BTRIM',
      description: '去除指定字符',
      syntax: "BTRIM(str, 'chars')",
      category: '字符串',
      params: 'str, chars',
    },
    {
      name: 'LENGTH',
      description: '字符串长度',
      syntax: 'LENGTH(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'CHAR_LENGTH',
      description: '字符数',
      syntax: 'CHAR_LENGTH(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'SUBSTRING',
      description: '截取字符串',
      syntax: 'SUBSTRING(str, start, length)',
      category: '字符串',
      params: 'str, start, length',
    },
    {
      name: 'SUBSTRING',
      description: '正则表达式截取',
      syntax: 'SUBSTRING(str FROM pattern)',
      category: '字符串',
      params: 'str FROM pattern',
    },
    {
      name: 'CONCAT',
      description: '连接字符串',
      syntax: 'CONCAT(str1, str2, ...)',
      category: '字符串',
      params: 'str1, str2, ...',
    },
    {
      name: 'CONCAT_WS',
      description: '带分隔符连接',
      syntax: "CONCAT_WS('-', str1, str2)",
      category: '字符串',
      params: 'sep, str1, str2, ...',
    },
    {
      name: 'COALESCE',
      description: '返回第一个非空值',
      syntax: 'COALESCE(expr1, expr2, ...)',
      category: '条件',
      params: 'expr1, expr2, ...',
    },
    {
      name: 'NULLIF',
      description: '如果相等则返回NULL',
      syntax: 'NULLIF(expr1, expr2)',
      category: '条件',
      params: 'expr1, expr2',
    },
    {
      name: 'GREATEST',
      description: '返回最大值',
      syntax: 'GREATEST(expr1, expr2, ...)',
      category: '条件',
      params: 'expr1, expr2, ...',
    },
    {
      name: 'LEAST',
      description: '返回最小值',
      syntax: 'LEAST(expr1, expr2, ...)',
      category: '条件',
      params: 'expr1, expr2, ...',
    },
    {
      name: 'CASE',
      description: '条件表达式',
      syntax: 'CASE WHEN condition THEN value ELSE default END',
      category: '条件',
      params: 'condition, value, default',
    },
    {
      name: 'ROUND',
      description: '四舍五入',
      syntax: 'ROUND(number, decimals)',
      category: '数值',
      params: 'number, decimals',
    },
    {
      name: 'FLOOR',
      description: '向下取整',
      syntax: 'FLOOR(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'CEIL',
      description: '向上取整',
      syntax: 'CEIL(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'CEILING',
      description: '向上取整',
      syntax: 'CEILING(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'ABS',
      description: '绝对值',
      syntax: 'ABS(number)',
      category: '数值',
      params: 'number',
    },
    { name: 'MOD', description: '取模', syntax: 'MOD(a, b)', category: '数值', params: 'a, b' },
    {
      name: 'POWER',
      description: '幂运算',
      syntax: 'POWER(base, exp)',
      category: '数值',
      params: 'base, exp',
    },
    {
      name: 'SQRT',
      description: '平方根',
      syntax: 'SQRT(number)',
      category: '数值',
      params: 'number',
    },
    { name: 'SUM', description: '求和', syntax: 'SUM(expr)', category: '聚合', params: 'expr' },
    { name: 'COUNT', description: '计数', syntax: 'COUNT(expr)', category: '聚合', params: 'expr' },
    { name: 'AVG', description: '平均值', syntax: 'AVG(expr)', category: '聚合', params: 'expr' },
    { name: 'MAX', description: '最大值', syntax: 'MAX(expr)', category: '聚合', params: 'expr' },
    { name: 'MIN', description: '最小值', syntax: 'MIN(expr)', category: '聚合', params: 'expr' },
    {
      name: 'NEXTVAL',
      description: '序列下一个值',
      syntax: "NEXTVAL('sequence_name')",
      category: '其他',
      params: 'sequence_name',
    },
    {
      name: 'CURRVAL',
      description: '序列当前值',
      syntax: "CURRVAL('sequence_name')",
      category: '其他',
      params: 'sequence_name',
    },
    {
      name: 'ROW_NUMBER',
      description: '行号',
      syntax: 'ROW_NUMBER() OVER (ORDER BY col)',
      category: '其他',
    },
    { name: 'DEFAULT', description: '使用列默认值', syntax: 'DEFAULT', category: '其他' },
  ],
  oracle: [
    { name: 'SYSDATE', description: '当前日期时间', syntax: 'SYSDATE', category: '日期时间' },
    {
      name: 'CURRENT_DATE',
      description: '当前会话日期',
      syntax: 'CURRENT_DATE',
      category: '日期时间',
    },
    {
      name: 'CURRENT_TIMESTAMP',
      description: '当前时间戳',
      syntax: 'CURRENT_TIMESTAMP',
      category: '日期时间',
    },
    {
      name: 'SYSTIMESTAMP',
      description: '系统时间戳',
      syntax: 'SYSTIMESTAMP',
      category: '日期时间',
    },
    {
      name: 'LOCALTIMESTAMP',
      description: '本地时间戳',
      syntax: 'LOCALTIMESTAMP',
      category: '日期时间',
    },
    {
      name: 'DBMS_RANDOM.STRING',
      description: '生成随机字符串',
      syntax: "DBMS_RANDOM.STRING('U', 10)",
      category: '字符串',
      params: 'format, length',
    },
    {
      name: 'RAWTOHEX',
      description: 'RAW转十六进制',
      syntax: 'RAWTOHEX(raw_data)',
      category: '字符串',
      params: 'raw_data',
    },
    {
      name: 'HEXTORAW',
      description: '十六进制转RAW',
      syntax: 'HEXTORAW(hex_data)',
      category: '字符串',
      params: 'hex_data',
    },
    {
      name: 'TO_CHAR',
      description: '格式化日期/数字',
      syntax: "TO_CHAR(date, 'YYYY-MM-DD')",
      category: '日期时间',
      params: 'value, format',
    },
    {
      name: 'TO_DATE',
      description: '字符串转日期',
      syntax: "TO_DATE('2024-01-01', 'YYYY-MM-DD')",
      category: '日期时间',
      params: 'str, format',
    },
    {
      name: 'TO_NUMBER',
      description: '字符串转数字',
      syntax: "TO_NUMBER('123')",
      category: '数值',
      params: 'str',
    },
    {
      name: 'ADD_MONTHS',
      description: '月份加法',
      syntax: 'ADD_MONTHS(date, n)',
      category: '日期时间',
      params: 'date, n',
    },
    {
      name: 'MONTHS_BETWEEN',
      description: '月份差值',
      syntax: 'MONTHS_BETWEEN(date1, date2)',
      category: '日期时间',
      params: 'date1, date2',
    },
    {
      name: 'LAST_DAY',
      description: '月份最后一天',
      syntax: 'LAST_DAY(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'NEXT_DAY',
      description: '下一个星期几',
      syntax: "NEXT_DAY(date, 'MONDAY')",
      category: '日期时间',
      params: 'date, day',
    },
    {
      name: 'EXTRACT',
      description: '提取日期部分',
      syntax: 'EXTRACT(YEAR FROM date)',
      category: '日期时间',
      params: 'field FROM date',
    },
    {
      name: 'TRUNC',
      description: '截断日期',
      syntax: 'TRUNC(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'ROUND',
      description: '四舍五入日期',
      syntax: 'ROUND(date, format)',
      category: '日期时间',
      params: 'date, format',
    },
    {
      name: 'UPPER',
      description: '转换为大写',
      syntax: 'UPPER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LOWER',
      description: '转换为小写',
      syntax: 'LOWER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'INITCAP',
      description: '首字母大写',
      syntax: 'INITCAP(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'TRIM',
      description: '去除首尾空格',
      syntax: 'TRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LTRIM',
      description: '去除左侧字符',
      syntax: 'LTRIM(str, chars)',
      category: '字符串',
      params: 'str, chars',
    },
    {
      name: 'RTRIM',
      description: '去除右侧字符',
      syntax: 'RTRIM(str, chars)',
      category: '字符串',
      params: 'str, chars',
    },
    {
      name: 'LENGTH',
      description: '字符串长度(字节)',
      syntax: 'LENGTH(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LENGTH2',
      description: '字符串长度(字符)',
      syntax: 'LENGTH2(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'SUBSTR',
      description: '截取字符串',
      syntax: 'SUBSTR(str, start, length)',
      category: '字符串',
      params: 'str, start, length',
    },
    {
      name: 'INSTR',
      description: '查找字符串位置',
      syntax: 'INSTR(str, substr)',
      category: '字符串',
      params: 'str, substr',
    },
    {
      name: 'CONCAT',
      description: '连接字符串',
      syntax: 'CONCAT(str1, str2)',
      category: '字符串',
      params: 'str1, str2',
    },
    {
      name: 'LPAD',
      description: '左侧填充',
      syntax: 'LPAD(str, length, pad)',
      category: '字符串',
      params: 'str, length, pad',
    },
    {
      name: 'RPAD',
      description: '右侧填充',
      syntax: 'RPAD(str, length, pad)',
      category: '字符串',
      params: 'str, length, pad',
    },
    {
      name: 'REPLACE',
      description: '替换字符串',
      syntax: 'REPLACE(str, old, new)',
      category: '字符串',
      params: 'str, old, new',
    },
    {
      name: 'TRANSLATE',
      description: '字符替换',
      syntax: 'TRANSLATE(str, from, to)',
      category: '字符串',
      params: 'str, from, to',
    },
    {
      name: 'NVL',
      description: '如果为空则返回默认值',
      syntax: 'NVL(expr, default_value)',
      category: '条件',
      params: 'expr, default_value',
    },
    {
      name: 'NVL2',
      description: '空值处理',
      syntax: 'NVL2(expr, not_null_val, null_val)',
      category: '条件',
      params: 'expr, not_null_val, null_val',
    },
    {
      name: 'NULLIF',
      description: '如果相等则返回NULL',
      syntax: 'NULLIF(expr1, expr2)',
      category: '条件',
      params: 'expr1, expr2',
    },
    {
      name: 'COALESCE',
      description: '返回第一个非空值',
      syntax: 'COALESCE(expr1, expr2, ...)',
      category: '条件',
      params: 'expr1, expr2, ...',
    },
    {
      name: 'DECODE',
      description: '条件匹配',
      syntax: 'DECODE(col, val1, result1, val2, result2, default)',
      category: '条件',
      params: 'col, val1, result1, ...',
    },
    {
      name: 'CASE',
      description: 'CASE表达式',
      syntax: 'CASE WHEN condition THEN value ELSE default END',
      category: '条件',
    },
    {
      name: 'ROUND',
      description: '四舍五入数字',
      syntax: 'ROUND(number, decimals)',
      category: '数值',
      params: 'number, decimals',
    },
    {
      name: 'TRUNC',
      description: '截断数字',
      syntax: 'TRUNC(number, decimals)',
      category: '数值',
      params: 'number, decimals',
    },
    {
      name: 'FLOOR',
      description: '向下取整',
      syntax: 'FLOOR(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'CEIL',
      description: '向上取整',
      syntax: 'CEIL(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'ABS',
      description: '绝对值',
      syntax: 'ABS(number)',
      category: '数值',
      params: 'number',
    },
    { name: 'MOD', description: '取模', syntax: 'MOD(a, b)', category: '数值', params: 'a, b' },
    {
      name: 'POWER',
      description: '幂运算',
      syntax: 'POWER(base, exp)',
      category: '数值',
      params: 'base, exp',
    },
    {
      name: 'SQRT',
      description: '平方根',
      syntax: 'SQRT(number)',
      category: '数值',
      params: 'number',
    },
    { name: 'SUM', description: '求和', syntax: 'SUM(expr)', category: '聚合', params: 'expr' },
    { name: 'COUNT', description: '计数', syntax: 'COUNT(expr)', category: '聚合', params: 'expr' },
    { name: 'AVG', description: '平均值', syntax: 'AVG(expr)', category: '聚合', params: 'expr' },
    { name: 'MAX', description: '最大值', syntax: 'MAX(expr)', category: '聚合', params: 'expr' },
    { name: 'MIN', description: '最小值', syntax: 'MIN(expr)', category: '聚合', params: 'expr' },
    { name: 'ROWNUM', description: '行号', syntax: 'ROWNUM', category: '其他' },
    {
      name: 'SEQ.NEXTVAL',
      description: '序列下一值',
      syntax: 'seq_name.NEXTVAL',
      category: '其他',
      params: 'seq_name',
    },
    {
      name: 'SEQ.CURRVAL',
      description: '序列当前值',
      syntax: 'seq_name.CURRVAL',
      category: '其他',
      params: 'seq_name',
    },
    { name: 'DEFAULT', description: '使用列默认值', syntax: 'DEFAULT', category: '其他' },
  ],
  sqlserver: [
    { name: 'GETDATE', description: '当前日期时间', syntax: 'GETDATE()', category: '日期时间' },
    {
      name: 'GETUTCDATE',
      description: '当前UTC时间',
      syntax: 'GETUTCDATE()',
      category: '日期时间',
    },
    {
      name: 'SYSDATETIME',
      description: '系统日期时间(高精度)',
      syntax: 'SYSDATETIME()',
      category: '日期时间',
    },
    {
      name: 'SYSUTCDATETIME',
      description: 'UTC日期时间(高精度)',
      syntax: 'SYSUTCDATETIME()',
      category: '日期时间',
    },
    {
      name: 'CURRENT_TIMESTAMP',
      description: '当前时间戳',
      syntax: 'CURRENT_TIMESTAMP',
      category: '日期时间',
    },
    { name: 'CURRENT_DATE', description: '当前日期', syntax: 'CURRENT_DATE', category: '日期时间' },
    { name: 'CURRENT_TIME', description: '当前时间', syntax: 'CURRENT_TIME', category: '日期时间' },
    { name: 'NEWID', description: '生成唯一标识符', syntax: 'NEWID()', category: '字符串' },
    {
      name: 'NEWSEQUENTIALID',
      description: '生成顺序唯一标识符',
      syntax: 'NEWSEQUENTIALID()',
      category: '字符串',
    },
    { name: 'RAND', description: '生成随机数', syntax: 'RAND()', category: '数值' },
    {
      name: 'RAND',
      description: '生成指定种子随机数',
      syntax: 'RAND(seed)',
      category: '数值',
      params: 'seed',
    },
    {
      name: 'CONVERT',
      description: '类型转换',
      syntax: 'CONVERT(VARCHAR, value)',
      category: '类型转换',
      params: 'type, value',
    },
    {
      name: 'CAST',
      description: '类型转换',
      syntax: 'CAST(value AS type)',
      category: '类型转换',
      params: 'value, type',
    },
    {
      name: 'FORMAT',
      description: '格式化日期',
      syntax: "FORMAT(date, 'yyyy-MM-dd')",
      category: '日期时间',
      params: 'date, format',
    },
    {
      name: 'DATEADD',
      description: '日期加法',
      syntax: 'DATEADD(day, 1, date)',
      category: '日期时间',
      params: 'part, number, date',
    },
    {
      name: 'DATEDIFF',
      description: '日期差值',
      syntax: 'DATEDIFF(day, date1, date2)',
      category: '日期时间',
      params: 'part, date1, date2',
    },
    {
      name: 'DATEPART',
      description: '提取日期部分',
      syntax: 'DATEPART(year, date)',
      category: '日期时间',
      params: 'part, date',
    },
    {
      name: 'YEAR',
      description: '获取年份',
      syntax: 'YEAR(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'MONTH',
      description: '获取月份',
      syntax: 'MONTH(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'DAY',
      description: '获取日',
      syntax: 'DAY(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'DATENAME',
      description: '获取日期名称',
      syntax: 'DATENAME(weekday, date)',
      category: '日期时间',
      params: 'part, date',
    },
    {
      name: 'EOMONTH',
      description: '月份最后一天',
      syntax: 'EOMONTH(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'SWITCHOFFSET',
      description: '时区偏移',
      syntax: 'SWITCHOFFSET(datetime, offset)',
      category: '日期时间',
      params: 'datetime, offset',
    },
    {
      name: 'TODATETIMEOFFSET',
      description: '带时区的日期',
      syntax: 'TODATETIMEOFFSET(datetime, offset)',
      category: '日期时间',
      params: 'datetime, offset',
    },
    {
      name: 'UPPER',
      description: '转换为大写',
      syntax: 'UPPER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LOWER',
      description: '转换为小写',
      syntax: 'LOWER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LEN',
      description: '字符串长度',
      syntax: 'LEN(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'DATALENGTH',
      description: '数据长度(字节)',
      syntax: 'DATALENGTH(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'SUBSTRING',
      description: '截取字符串',
      syntax: 'SUBSTRING(str, start, length)',
      category: '字符串',
      params: 'str, start, length',
    },
    {
      name: 'LEFT',
      description: '左侧截取',
      syntax: 'LEFT(str, length)',
      category: '字符串',
      params: 'str, length',
    },
    {
      name: 'RIGHT',
      description: '右侧截取',
      syntax: 'RIGHT(str, length)',
      category: '字符串',
      params: 'str, length',
    },
    {
      name: 'CHARINDEX',
      description: '查找字符串位置',
      syntax: 'CHARINDEX(substr, str)',
      category: '字符串',
      params: 'substr, str',
    },
    {
      name: 'PATINDEX',
      description: '模式匹配位置',
      syntax: "PATINDEX('%pattern%', str)",
      category: '字符串',
      params: 'pattern, str',
    },
    {
      name: 'CONCAT',
      description: '连接字符串',
      syntax: 'CONCAT(str1, str2, ...)',
      category: '字符串',
      params: 'str1, str2, ...',
    },
    {
      name: 'CONCAT_WS',
      description: '带分隔符连接',
      syntax: "CONCAT_WS('-', str1, str2)",
      category: '字符串',
      params: 'sep, str1, str2, ...',
    },
    {
      name: 'STRING_AGG',
      description: '字符串聚合',
      syntax: "STRING_AGG(col, ',') WITHIN GROUP (ORDER BY col)",
      category: '字符串',
    },
    {
      name: 'STRING_SPLIT',
      description: '字符串分割',
      syntax: "STRING_SPLIT(str, ',')",
      category: '字符串',
      params: 'str, separator',
    },
    {
      name: 'TRIM',
      description: '去除首尾空格',
      syntax: 'TRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LTRIM',
      description: '去除左侧空格',
      syntax: 'LTRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'RTRIM',
      description: '去除右侧空格',
      syntax: 'RTRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'REPLACE',
      description: '替换字符串',
      syntax: 'REPLACE(str, old, new)',
      category: '字符串',
      params: 'str, old, new',
    },
    {
      name: 'STUFF',
      description: '删除并插入',
      syntax: 'STUFF(str, start, length, new_str)',
      category: '字符串',
      params: 'str, start, length, new_str',
    },
    {
      name: 'REPLICATE',
      description: '重复字符串',
      syntax: 'REPLICATE(str, count)',
      category: '字符串',
      params: 'str, count',
    },
    {
      name: 'REVERSE',
      description: '反转字符串',
      syntax: 'REVERSE(str)',
      category: '字符串',
      params: 'str',
    },
    { name: 'SPACE', description: '生成空格', syntax: 'SPACE(n)', category: '字符串', params: 'n' },
    {
      name: 'ISNULL',
      description: '如果为空则返回默认值',
      syntax: 'ISNULL(expr, default_value)',
      category: '条件',
      params: 'expr, default_value',
    },
    {
      name: 'NULLIF',
      description: '如果相等则返回NULL',
      syntax: 'NULLIF(expr1, expr2)',
      category: '条件',
      params: 'expr1, expr2',
    },
    {
      name: 'COALESCE',
      description: '返回第一个非空值',
      syntax: 'COALESCE(expr1, expr2, ...)',
      category: '条件',
      params: 'expr1, expr2, ...',
    },
    {
      name: 'IIF',
      description: '条件表达式',
      syntax: 'IIF(condition, true_val, false_val)',
      category: '条件',
      params: 'condition, true_val, false_val',
    },
    {
      name: 'CHOOSE',
      description: '选择值',
      syntax: 'CHOOSE(index, val1, val2, ...)',
      category: '条件',
      params: 'index, val1, val2, ...',
    },
    {
      name: 'CASE',
      description: 'CASE表达式',
      syntax: 'CASE WHEN condition THEN value ELSE default END',
      category: '条件',
    },
    {
      name: 'ROUND',
      description: '四舍五入',
      syntax: 'ROUND(number, length)',
      category: '数值',
      params: 'number, length',
    },
    {
      name: 'FLOOR',
      description: '向下取整',
      syntax: 'FLOOR(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'CEILING',
      description: '向上取整',
      syntax: 'CEILING(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'ABS',
      description: '绝对值',
      syntax: 'ABS(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'POWER',
      description: '幂运算',
      syntax: 'POWER(base, exp)',
      category: '数值',
      params: 'base, exp',
    },
    {
      name: 'SQRT',
      description: '平方根',
      syntax: 'SQRT(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'SQUARE',
      description: '平方',
      syntax: 'SQUARE(number)',
      category: '数值',
      params: 'number',
    },
    { name: 'SUM', description: '求和', syntax: 'SUM(expr)', category: '聚合', params: 'expr' },
    { name: 'COUNT', description: '计数', syntax: 'COUNT(expr)', category: '聚合', params: 'expr' },
    { name: 'AVG', description: '平均值', syntax: 'AVG(expr)', category: '聚合', params: 'expr' },
    { name: 'MAX', description: '最大值', syntax: 'MAX(expr)', category: '聚合', params: 'expr' },
    { name: 'MIN', description: '最小值', syntax: 'MIN(expr)', category: '聚合', params: 'expr' },
    {
      name: 'IDENT_CURRENT',
      description: '获取标识列当前值',
      syntax: "IDENT_CURRENT('table')",
      category: '其他',
      params: 'table',
    },
    {
      name: 'SCOPE_IDENTITY',
      description: '当前作用域标识值',
      syntax: 'SCOPE_IDENTITY()',
      category: '其他',
    },
    { name: '@@IDENTITY', description: '会话标识值', syntax: '@@IDENTITY', category: '其他' },
    { name: 'DEFAULT', description: '使用列默认值', syntax: 'DEFAULT', category: '其他' },
  ],
  dm: [
    { name: 'SYSDATE', description: '当前日期时间', syntax: 'SYSDATE', category: '日期时间' },
    { name: 'SYSTIME', description: '当前时间', syntax: 'SYSTIME', category: '日期时间' },
    {
      name: 'SYSTIMESTAMP',
      description: '当前时间戳',
      syntax: 'SYSTIMESTAMP',
      category: '日期时间',
    },
    { name: 'CURRENT_DATE', description: '当前日期', syntax: 'CURRENT_DATE', category: '日期时间' },
    { name: 'CURRENT_TIME', description: '当前时间', syntax: 'CURRENT_TIME', category: '日期时间' },
    {
      name: 'CURRENT_TIMESTAMP',
      description: '当前时间戳',
      syntax: 'CURRENT_TIMESTAMP',
      category: '日期时间',
    },
    { name: 'NOW', description: '当前日期时间', syntax: 'NOW()', category: '日期时间' },
    { name: 'GETDATE', description: '获取当前日期时间', syntax: 'GETDATE()', category: '日期时间' },
    { name: 'GUID', description: '生成唯一标识符', syntax: 'GUID()', category: '字符串' },
    { name: 'RANDOM', description: '生成随机数', syntax: 'RANDOM()', category: '数值' },
    {
      name: 'TO_CHAR',
      description: '格式化日期/数字',
      syntax: "TO_CHAR(date, 'YYYY-MM-DD')",
      category: '日期时间',
      params: 'value, format',
    },
    {
      name: 'TO_DATE',
      description: '字符串转日期',
      syntax: "TO_DATE('2024-01-01', 'YYYY-MM-DD')",
      category: '日期时间',
      params: 'str, format',
    },
    {
      name: 'TO_NUMBER',
      description: '字符串转数字',
      syntax: "TO_NUMBER('123')",
      category: '数值',
      params: 'str',
    },
    {
      name: 'ADD_DAYS',
      description: '日期加天数',
      syntax: 'ADD_DAYS(date, n)',
      category: '日期时间',
      params: 'date, n',
    },
    {
      name: 'ADD_MONTHS',
      description: '月份加法',
      syntax: 'ADD_MONTHS(date, n)',
      category: '日期时间',
      params: 'date, n',
    },
    {
      name: 'MONTHS_BETWEEN',
      description: '月份差值',
      syntax: 'MONTHS_BETWEEN(date1, date2)',
      category: '日期时间',
      params: 'date1, date2',
    },
    {
      name: 'LAST_DAY',
      description: '月份最后一天',
      syntax: 'LAST_DAY(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'NEXT_DAY',
      description: '下一个星期几',
      syntax: "NEXT_DAY(date, 'MONDAY')",
      category: '日期时间',
      params: 'date, day',
    },
    {
      name: 'EXTRACT',
      description: '提取日期部分',
      syntax: 'EXTRACT(YEAR FROM date)',
      category: '日期时间',
      params: 'field FROM date',
    },
    {
      name: 'TRUNC',
      description: '截断日期',
      syntax: 'TRUNC(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'ROUND',
      description: '四舍五入日期',
      syntax: 'ROUND(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'WEEK',
      description: '获取周数',
      syntax: 'WEEK(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'DAYOFWEEK',
      description: '获取星期几',
      syntax: 'DAYOFWEEK(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'DAYOFYEAR',
      description: '一年中第几天',
      syntax: 'DAYOFYEAR(date)',
      category: '日期时间',
      params: 'date',
    },
    {
      name: 'UPPER',
      description: '转换为大写',
      syntax: 'UPPER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LOWER',
      description: '转换为小写',
      syntax: 'LOWER(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'INITCAP',
      description: '首字母大写',
      syntax: 'INITCAP(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'TRIM',
      description: '去除首尾空格',
      syntax: 'TRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LTRIM',
      description: '去除左侧空格',
      syntax: 'LTRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'RTRIM',
      description: '去除右侧空格',
      syntax: 'RTRIM(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'LENGTH',
      description: '字符串长度',
      syntax: 'LENGTH(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'CHAR_LENGTH',
      description: '字符数',
      syntax: 'CHAR_LENGTH(str)',
      category: '字符串',
      params: 'str',
    },
    {
      name: 'SUBSTR',
      description: '截取字符串',
      syntax: 'SUBSTR(str, start, length)',
      category: '字符串',
      params: 'str, start, length',
    },
    {
      name: 'SUBSTRING',
      description: '截取字符串',
      syntax: 'SUBSTRING(str, start, length)',
      category: '字符串',
      params: 'str, start, length',
    },
    {
      name: 'INSTR',
      description: '查找字符串位置',
      syntax: 'INSTR(str, substr)',
      category: '字符串',
      params: 'str, substr',
    },
    {
      name: 'CONCAT',
      description: '连接字符串',
      syntax: 'CONCAT(str1, str2)',
      category: '字符串',
      params: 'str1, str2',
    },
    {
      name: 'LPAD',
      description: '左侧填充',
      syntax: 'LPAD(str, length, pad)',
      category: '字符串',
      params: 'str, length, pad',
    },
    {
      name: 'RPAD',
      description: '右侧填充',
      syntax: 'RPAD(str, length, pad)',
      category: '字符串',
      params: 'str, length, pad',
    },
    {
      name: 'REPLACE',
      description: '替换字符串',
      syntax: 'REPLACE(str, old, new)',
      category: '字符串',
      params: 'str, old, new',
    },
    {
      name: 'TRANSLATE',
      description: '字符替换',
      syntax: 'TRANSLATE(str, from, to)',
      category: '字符串',
      params: 'str, from, to',
    },
    {
      name: 'DECODE',
      description: '条件匹配',
      syntax: 'DECODE(col, val1, result1, val2, result2, default)',
      category: '条件',
      params: 'col, val1, result1, ...',
    },
    {
      name: 'CASE',
      description: 'CASE表达式',
      syntax: 'CASE WHEN condition THEN value ELSE default END',
      category: '条件',
    },
    {
      name: 'NVL',
      description: '如果为空则返回默认值',
      syntax: 'NVL(expr, default_value)',
      category: '条件',
      params: 'expr, default_value',
    },
    {
      name: 'NVL2',
      description: '空值处理',
      syntax: 'NVL2(expr, not_null_val, null_val)',
      category: '条件',
      params: 'expr, not_null_val, null_val',
    },
    {
      name: 'NULLIF',
      description: '如果相等则返回NULL',
      syntax: 'NULLIF(expr1, expr2)',
      category: '条件',
      params: 'expr1, expr2',
    },
    {
      name: 'COALESCE',
      description: '返回第一个非空值',
      syntax: 'COALESCE(expr1, expr2, ...)',
      category: '条件',
      params: 'expr1, expr2, ...',
    },
    {
      name: 'IFNULL',
      description: '如果为空则返回默认值',
      syntax: 'IFNULL(expr, default_value)',
      category: '条件',
      params: 'expr, default_value',
    },
    {
      name: 'IFF',
      description: '条件表达式',
      syntax: 'IFF(condition, true_val, false_val)',
      category: '条件',
      params: 'condition, true_val, false_val',
    },
    {
      name: 'ROUND',
      description: '四舍五入数字',
      syntax: 'ROUND(number, decimals)',
      category: '数值',
      params: 'number, decimals',
    },
    {
      name: 'TRUNC',
      description: '截断数字',
      syntax: 'TRUNC(number, decimals)',
      category: '数值',
      params: 'number, decimals',
    },
    {
      name: 'FLOOR',
      description: '向下取整',
      syntax: 'FLOOR(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'CEIL',
      description: '向上取整',
      syntax: 'CEIL(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'ABS',
      description: '绝对值',
      syntax: 'ABS(number)',
      category: '数值',
      params: 'number',
    },
    { name: 'MOD', description: '取模', syntax: 'MOD(a, b)', category: '数值', params: 'a, b' },
    {
      name: 'POWER',
      description: '幂运算',
      syntax: 'POWER(base, exp)',
      category: '数值',
      params: 'base, exp',
    },
    {
      name: 'SQRT',
      description: '平方根',
      syntax: 'SQRT(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'SIGN',
      description: '符号函数',
      syntax: 'SIGN(number)',
      category: '数值',
      params: 'number',
    },
    { name: 'EXP', description: '指数', syntax: 'EXP(number)', category: '数值', params: 'number' },
    {
      name: 'LN',
      description: '自然对数',
      syntax: 'LN(number)',
      category: '数值',
      params: 'number',
    },
    {
      name: 'LOG',
      description: '对数',
      syntax: 'LOG(base, number)',
      category: '数值',
      params: 'base, number',
    },
    { name: 'SUM', description: '求和', syntax: 'SUM(expr)', category: '聚合', params: 'expr' },
    { name: 'COUNT', description: '计数', syntax: 'COUNT(expr)', category: '聚合', params: 'expr' },
    { name: 'AVG', description: '平均值', syntax: 'AVG(expr)', category: '聚合', params: 'expr' },
    { name: 'MAX', description: '最大值', syntax: 'MAX(expr)', category: '聚合', params: 'expr' },
    { name: 'MIN', description: '最小值', syntax: 'MIN(expr)', category: '聚合', params: 'expr' },
    {
      name: 'SEQUENCE.NEXTVAL',
      description: '序列下一值',
      syntax: 'seq_name.NEXTVAL',
      category: '其他',
      params: 'seq_name',
    },
    {
      name: 'SEQUENCE.CURRVAL',
      description: '序列当前值',
      syntax: 'seq_name.CURRVAL',
      category: '其他',
      params: 'seq_name',
    },
    { name: 'IDENTITY', description: '自增标识', syntax: 'IDENTITY', category: '其他' },
    { name: 'DEFAULT', description: '使用列默认值', syntax: 'DEFAULT', category: '其他' },
  ],
}

/**
 * 获取数据库类型显示名称
 * @param {string} dbType - 数据库类型代码
 * @returns {string} 数据库类型显示名称
 */
export function getDatabaseTypeName(dbType) {
  const typeNames = {
    mysql: 'MySQL',
    postgresql: 'PostgreSQL',
    oracle: 'Oracle',
    sqlserver: 'SQL Server',
    dm: '达梦 (DM)',
  }
  return typeNames[dbType] || dbType
}

/**
 * 获取指定数据库类型的函数列表
 * @param {string} dbType - 数据库类型
 * @returns {Array} 函数列表
 */
export function getDatabaseFunctions(dbType) {
  return DatabaseFunctions[dbType] || DatabaseFunctions.mysql
}

/**
 * 获取所有支持的数据库类型
 * @returns {Array} 数据库类型列表
 */
export function getSupportedDatabaseTypes() {
  return [
    { value: 'mysql', label: 'MySQL' },
    { value: 'postgresql', label: 'PostgreSQL' },
    { value: 'oracle', label: 'Oracle' },
    { value: 'sqlserver', label: 'SQL Server' },
    { value: 'dm', label: '达梦 (DM)' },
  ]
}

/**
 * 根据函数名获取函数信息
 * @param {string} dbType - 数据库类型
 * @param {string} funcName - 函数名
 * @returns {Object|null} 函数信息
 */
export function getFunctionInfo(dbType, funcName) {
  const functions = getDatabaseFunctions(dbType)
  return functions.find((f) => f.name === funcName) || null
}

/**
 * 获取函数的正确调用语法
 * @param {string} dbType - 数据库类型
 * @param {string} funcName - 函数名
 * @returns {string} 函数调用语法
 */
export function getFunctionSyntax(dbType, funcName) {
  const funcInfo = getFunctionInfo(dbType, funcName)
  if (funcInfo) {
    return funcInfo.syntax
  }
  return `${funcName}()`
}
